// src/lib/Footer.svelte
<footer class="border-t-bgborder bg-bgsecondary py-8">
	<div
		class="max-w-8xl container mx-auto flex flex-col content-center items-center justify-between space-y-6 px-3 align-middle lg:flex-row lg:space-y-0 xl:px-0"
	>
		<div class="text-center text-gray-300 lg:text-left">
			<ul>
				<li>Discord: driedsponge</li>
				<li>
					GitHub: <a
						class="underline"
						target="_blank"
						href="https://github.com/driedsponge">driedsponge</a
					>
				</li>
				<li>
					<a
						class="underline"
						target="_blank"
						href="https://github.com/driedsponge/driedsponge.net">Website Source Code</a
					>
				</li>
			</ul>
		</div>

		<div>
			<p class="text-center text-3xl font-extrabold text-white lg:text-right">
				<span class="text-myblue">J</span>T
			</p>
			<p class="text-xs text-gray-400">© 2023 Jordan Tucker</p>
		</div>
	</div>
</footer>

// src/resources/js/components/includes/Footer/Footer.vue
<template>
    <footer class="py-5 m-3">
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column">
                    <div class="content has-text-white has-text-centered-mobile">
                        <p>&copy; Jordan Tucker 2021</p>
                    </div>
                </div>
                <div class="column has-text-right has-text-centered-mobile">
                    <p class="buttons has-addons  is-inline-block">
                        <Footerlink to="https://github.com/driedsponge/driedsponge.net">
                            <Icon icon="fab fa-github" class="is-left"/>
                            <span>Source Code</span>
                        </Footerlink>
                        <Footerlink :to="{ name: 'home', hash:'#contact'}">
                            <Icon icon="fas fa-envelope" class="is-left"/>
                            <span>Contact</span>
                        </Footerlink>
                        <Loginbutton/>
                    </p>
                </div>
            </div>

        </div>
    </footer>
</template>
<script>
import Icon from "../../text/Icon";
import Loginbutton from "./Loginbutton";
import Footerlink from "./Footerlink";

export default {
    name: "Footer",
    components: {Footerlink, Loginbutton, Icon}
}
</script>
