// src/lib/Footer.svelte
<footer class="border-t-bgborder bg-bgsecondary py-8">
	<div
		class="max-w-8xl container mx-auto flex flex-col content-center items-center justify-between space-y-6 px-3 align-middle lg:flex-row lg:space-y-0 xl:px-0"
	>
		<div class="text-center text-gray-300 lg:text-left">
			<ul>
				<li>Discord: driedsponge</li>
				<li>
					GitHub: <a
						class="underline"
						target="_blank"
						href="https://github.com/driedsponge">driedsponge</a
					>
				</li>
				<li>
					<a
						class="underline"
						target="_blank"
						href="https://github.com/driedsponge/driedsponge.net">Website Source Code</a
					>
				</li>
			</ul>
		</div>

		<div>
			<p class="text-center text-3xl font-extrabold text-white lg:text-right">
				<span class="text-myblue">J</span>T
			</p>
			<p class="text-xs text-gray-400">© 2023 Jordan Tucker</p>
		</div>
	</div>
</footer>

// src/resources/js/components/includes/Footer.vue
<template>
    <footer class="py-5 m-3" >
        <div class="container">
            <div class="level">
                <div class="level-left">
                    <div class="level-item">
                        <div class="content has-text-white ">
                            <p>&copy; Jordan Tucker 2020</p>
                        </div>
                    </div>
                </div>
                <div class="level-right">
                    <div class="level-item">
                        <div class="field has-addons level-item">
                            <p class="control">
                                <a href="https://github.com/driedsponge" target="_blank" class="button is-light is-outlined">
                                    <Icon icon="fab fa-github" class="is-left" />
                                    <span>Source Code</span>
                                </a>
                            </p>
                            <p class="control">
                                <router-link :to="{ name: 'home'}" class="button is-light is-outlined">
                                    <Icon icon="fas fa-envelope" class="is-left" />
                                    <span>Contact</span>
                                </router-link>
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </footer>
</template>
<script>
import Icon from "../text/Icon";
export default {
    name: "Footer",
    components: {Icon}
}
</script>
